### ISSUE TITLE
[UWP] Make it so we you still use live visual tree when debugging on Windows

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno.xamlmerge.task#45] opened 2022-03-15 15:33 UTC
The XamlMerge make it so we can't access style of component with LiveVisualTree while debugging on windows. 

## What would you like to be added:
Have XamlMerge disabled on UPW or at the very least disabled when debugging.

## Why is this needed:
LiveVisualTree is an important tool when working on front end issues and features.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

**Comment by jeromelaban** [comment] 2022-03-15 15:42
Thanks for the report. This is a duplicate of https://github.com/unoplatform/uno.xamlmerge.task/issues/40

**Closed as completed by jeromelaban** 2022-03-15 15:42 UTC
Labels: kind/enhancement, triage/untriaged
